apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stg354
  name: producer
spec:
  selector:
    matchLabels:
      run: producer
  replicas: 1
  template:
    metadata:
      labels:
        run: producer
    spec:
      serviceAccountName: stg354-sa
      containers:
        - name: stg354-producer
          image: public.ecr.aws/a8x8v1t1/stg354:producer-latest
          imagePullPolicy: Always
          volumeMounts:
            - name: efs-persistent
              mountPath: /efs1
      volumes:
        - name: efs-persistent
          persistentVolumeClaim:
            claimName: efs-claim

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stg354
  name: consumer
spec:
  selector:
    matchLabels:
      run: consumer
  replicas: 1
  template:
    metadata:
      labels:
        run: consumer
    spec:
      serviceAccountName: stg354-sa
      containers:
        - name: stg354-consumer
          image: public.ecr.aws/a8x8v1t1/stg354:consumer-latest
          imagePullPolicy: Always
          volumeMounts:
            - name: efs-persistent
              mountPath: /efs1
      volumes:
        - name: efs-persistent
          persistentVolumeClaim:
            claimName: efs-claim

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stg354
  name: controller
spec:
  selector:
    matchLabels:
      run: controller
  replicas: 1
  template:
    metadata:
      labels:
        run: controller
        app.kubernetes.io/name: controller
    spec:
      containers:
        - name: stg354-controller
          image: public.ecr.aws/a8x8v1t1/stg354:controller-latest
          imagePullPolicy: Always
          volumeMounts:
            - name: efs-persistent
              mountPath: /efs1
          ports:
            - containerPort: 5000
              name: http-flask-svc
      volumes:
        - name: efs-persistent
          persistentVolumeClaim:
            claimName: efs-claim

---

apiVersion: v1
kind: Service
metadata:
  namespace: stg354
  name: controller-svc
spec:
  selector:
    app.kubernetes.io/name: controller
  ports:
    - name: controller-svc-port
      protocol: TCP
      port: 80
      targetPort: http-flask-svc


