apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 'secondary'
  region: 'eu-west-2'
  version: '1.28'
  tags:
    EnvironmentName: 'dr'

iam:
  withOIDC: true

addons:
- name: aws-efs-csi-driver

vpc:
  subnets: 
    private:
      private1:
          id: 'subnet-09def6e1d44eb24cd'
      private2:
          id: 'subnet-008c78300739fdf90'
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

managedNodeGroups:
- name: ng
  desiredCapacity: 2
  instanceType: t3.medium
  privateNetworking: true
  subnets: 
    - private1
    - private2
